from Workload import Workload
from AzureWorkload import AzureWorkload
from BitbrainWorkload_GaussianDistribution import BWGD
from BitbrainWorkload2 import BWGD2
from StaticWorkload_StaticDistribution import SWSD
